# Generated by Django 2.2.6 on 2019-10-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_datetime', models.DateTimeField()),
                ('appointment_status', models.CharField(choices=[('P', 'Past'), ('F', 'Forthcoming'), ('C', 'Cancelled')], max_length=2)),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('prescribtion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('specialization', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('education', models.CharField(max_length=40)),
                ('experience', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'doctors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
            ],
            options={
                'db_table': 'patients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('beds', models.IntegerField()),
            ],
            options={
                'db_table': 'rooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('surgery_id', models.AutoField(primary_key=True, serialize=False)),
                ('surgery_datetime', models.DateTimeField()),
                ('surgery_status', models.CharField(choices=[('S', 'Successful'), ('U', 'Unsuccessful'), ('F', 'Forthcoming'), ('C', 'Cancelled')], max_length=2)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='surgery_database.Appointment')),
            ],
            options={
                'db_table': 'surgeries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('hospitalization_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='surgery_database.Patient')),
                ('room_number', models.ForeignKey(db_column='room_number', on_delete=django.db.models.deletion.CASCADE, to='surgery_database.Room')),
            ],
            options={
                'db_table': 'hospitalization',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='surgery_database.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='surgery_database.Patient'),
        ),
    ]
