# Generated by Django 2.2.6 on 2019-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('P', 'Past'), ('F', 'Forthcoming'), ('C', 'Cancelled')], max_length=17),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=17),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=17),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_status',
            field=models.CharField(choices=[('S', 'Successful'), ('U', 'Unsuccessful'), ('F', 'Forthcoming'), ('C', 'Cancelled')], max_length=20),
        ),
    ]
