# Generated by Django 2.2.6 on 2019-10-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_database', '0002_auto_20191010_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='surgery',
            old_name='appointment',
            new_name='appointment_id',
        ),
    ]
