# Generated by Django 2.2.6 on 2019-10-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_database', '0003_auto_20191010_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalization',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
