# Generated by Django 2.2.7 on 2019-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_database', '0004_auto_20191010_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('P', 'Past'), ('F', 'Forthcoming')], default='F', max_length=17),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('CR', 'Colon and Rectal Surgery'), ('G', 'General Surgery'), ('T', 'Thoracic Surgery'), ('N', 'Neurological Surgery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_status',
            field=models.CharField(choices=[('S', 'Successful'), ('U', 'Unsuccessful'), ('F', 'Forthcoming')], max_length=20),
        ),
    ]
