# Generated by Django 2.2.7 on 2019-11-26 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_database', '0005_auto_20191126_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='check_in_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
