# Generated by Django 2.2.7 on 2019-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_database', '0006_auto_20191126_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_hospitalized',
            field=models.BooleanField(default=False),
        ),
    ]
